trigger:
  - main

variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'
  projectName: 'RapidDapr.PubSub.sln'


pool:
  vmImage: $(vmImageName)


steps:
- task: UseDotNet@2
  displayName: 'Install .NET 6 sdk'
  inputs:
    version: 6.x
    packageType: sdk
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '$(projectName)'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

